version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: CMPU4003mariadb
    environment: 
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: mariadb-week1
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql